# Project properties & versions
mod_group=net.yourpackage.yourmod
mod_id=vegandelight
mod_name=Vegan Delight
mod_authors=SayWhatSayMon & Player005
mod_version=2.0.0-beta4
mod_description=Adds new ingredients to make food vegan.

# The license for your mod - see https://choosealicense.com/
mod_license=LGPLv3

java_version=21

# The minecraft version used for compiling and testing
minecraft_version=1.21.1
# The minecraft version ranges for fabric.mod.json and neoforge.mods.toml respectively
mc_versions_fabric=>=1.21
mc_versions_neo=[1.21,)
# parchment version in the pattern mc_version:parchment_version
# check https://parchmentmc.org/docs/getting-started for latest version
parchment_version=1.21:2024.07.28

# The neoforge version used for compiling and testing
neoforge_version=21.1.209
# range of allowed neo loader versions (used in neoforge.mods.toml)
neo_loader_version_range=*

fd_version=1.21.1-1.2.9
fdrf_version=1.21.1-3.1.2+refabricated
recipemod_version=0.1.1
midnight_version=1.9.2+1.21.1

# check these versions on https://fabricmc.net/develop/
fabric_loader_version=0.16.7
# if you don't need fabric api, you can remove this line as well as the one in fabric/build.gradle.kts
fabric_api_version=0.107.0+1.21.1

# See 'Platform conversions.md'
handle_fluid_unit_conversion=true
unified_load_conditions=true

# Done to improve gradle performance.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
