name: Build and Release

on:
  release:
    types:
      - published

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload forge artifacts to Modrinth and Curseforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Na8nA0jA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 928290
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: build/libs_forge/!(*-@(dev|sources|all)).jar
          game-versions: ">=1.21"

          version-type: release
          loaders: neoforge
          version-resolver: latest
        
          dependencies: farmers-delight

      - name: Upload fabric artifacts to Modrinth and GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: Na8nA0jA
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          curseforge-id: 928290
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: build/libs_fabric/!(*-@(dev|sources|all)).jar
          
          version-type: release
          loaders: fabric quilt
          version-resolver: latest

          dependencies: |
            fabric-api
            farmers-delight-refabricated
            farmers-delight-fabric(incompatible)

